# Generated by Django 2.1.15 on 2022-05-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmodel',
            name='autorizations',
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='autorization',
            field=models.TextField(db_column='autorizations', default='no'),
            preserve_default=False,
        ),
    ]
